### ISSUE TITLE
Is there a version for .NET Framework?

### ISSUE THREAD

**Issue by vunb** [aratomo-arazon/WFLite#1]
I have some projects not using .net core, so i can use this library. Do you have a plan for supporting .Net Framework?

**Comment by aratomo-arazon** [comment]
Thanks for your comment! 
I will change the target framework from .NET Core to .NET Standard to support .NET Framework in the next release.
Please wait.

**Comment by aratomo-arazon** [comment]
I fixed this issue in v1.1.2.
