### ISSUE TITLE
Unexpected behavior of SequenceActivity with a SequenceActivity inside

### ISSUE THREAD

**Issue by jclago** [aratomo-arazon/WFLite#2]
Hi there.
I'm currently using the `WFLite` library, it is really useful and is great for lightweight workflows.

I have a `SequenceActivity` running inside another `SequenceActivity`, and it fails to determine if the inside `SequenceActivity` is stopped. 
When one activity inside a `SequenceActivity` returns `false`, the `SequenceActivity` status is `ActivityStatus.Stopping` and then it not hits the:
```c#
if (_current.Status.IsStopped() || _current.Status.IsSuspended())
{
 return;
}
```
causing the next activity in the sequence to get executed.

Sample:

```c#
var seqActivity = new SequenceActivity()
            {
                Activities = new List<IActivity>()
                {
                    new SequenceActivity()
                    {
                        Activities = new List<IActivity>()
                        {
                            new Act1_1(),
                            new Act1_2(), //returns false
                            new Act1_3(),
                        }
                    },
                    new Act2_1(),                    
                }
            };

await seqActivity.Start();
```
Output:
```console
Act1_1 exec
Act1_2 exec
Act2_1 exec
```

Question: Is this the expected behavior?

I'm willing to contribute to this project.

**Comment by aratomo-arazon** [comment]
Thank you for your issue report and so sorry for my late reply.
Act2_1 must not be executed. I fixed this bug. Could you try new code?
Thank you for your contribution!
